version: '3.8'

services:
  product-postgres:
    image: postgres
    container_name: product-postgres
    read_only: true
    environment:
      - POSTGRES_USER=product
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=productDb
    expose:
      - "5432"  # PostgreSQL varsayılan portu
    ports:
      - "5491:5432"  # Dışarıdan 5490 portunu PostgreSQL 5432 portuna yönlendirme
    tmpfs:
      - /tmp
      - /run
      - /run/postgresql
    volumes:
      - product-volume:/var/lib/postgresql/data

volumes:
  product-volume:
