server:
  port: 6614

spring:
  datasource:
    url: jdbc:h2:mem:discountClientDB
    driverClassName: org.h2.Driver
    username: discount
    password: admin123
  h2:
    console:
      enabled: true
      path: /h2-console
      web-allow-others: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

grpc:
  client:
    grpc-discount-service:
      address: static://138.68.104.56:9011
      negotiation-type: plaintext
    grpc-category-service:
      address: static://138.68.104.56:9011
      negotiation-type: plaintext
    grpc-discountCategory-service:
      address: static://138.68.104.56:9011
      negotiation-type: plaintext
